FROM node:14.15.0

ENV CHROME_BIN=chromium

WORKDIR /app

RUN apt-get update && apt-get install -y chromium
RUN npm install eslint

COPY package-lock.json .
COPY package.json .

RUN npm i && npm i -g @angular/cli

COPY . .
